### ISSUE TITLE
coppy puts stdin, not stdout, into clipboard

### ISSUE THREAD

**Issue by phrohdoh** [costa86/coppy#1]
I understand that in the demonstrated uses it takes the prior command's stdout but data can be fed to coppy('s stdin) in ways that are not piping stdout into coppy, so the wording could mislead users.

**Comment by costa86** [comment]
Could you provide an example? Thanks!

**Comment by phrohdoh** [comment]
The comments on this StackOverflow answer illustrate some of the ways stdin may be populated:
 https://stackoverflow.com/questions/1987105/redirect-standard-input-dynamically-in-a-bash-script#comment1904312_1987259

` coppy <(cat ~/.zshrc)` for example

**Comment by costa86** [comment]
I've just tried and it does not work with this syntax...Did it work with you? Did it populate your clipboard?
